name: auctobid_mobile
description: "AUCTOBID - Sistem Lelang Online Mobile App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  flutter_local_notifications: ^19.5.0
  web_socket_channel: ^3.0.3
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AUCTOBID-Favicon.png"
  adaptive_icon_background: "#8B4513"
  adaptive_icon_foreground: "assets/images/AUCTOBID-Favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
